name = "Games"
uuid = "eb50afb4-6f20-4b37-9b66-473e668300bf"
authors = ["Davide Fioriti <fioritidavidesubs@gmail.com>"]
version = "0.1.0"

[deps]
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
ExportAll = "ad2082ca-a69e-11e9-38fa-e96309a31fe4"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
Formatting = "59287772-0a20-5a39-b81b-1366585eb4c0"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
ProgressBars = "49802e3a-d2f1-5c88-81d8-b72133a6f568"

[compat]
julia = "1"
